steps:
- name: golang
  entrypoint: go
  args: ['install', 'github.com/google/ko@v0.9.3']
- name: golang
  entrypoint: bash
  args: ['-c', 'KO_DOCKER_REPO="gcr.io/allstar-ossf" /go/bin/ko publish ./cmd/allstar > container']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: ['-c', 'gcloud app deploy --project=allstar-ossf --image-url $(cat container)']
options:
  volumes:
  - name: go-modules
    path: /go
