// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: alert.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlertSinkClient is the client API for AlertSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertSinkClient interface {
	Alert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error)
}

type alertSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertSinkClient(cc grpc.ClientConnInterface) AlertSinkClient {
	return &alertSinkClient{cc}
}

func (c *alertSinkClient) Alert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error) {
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, "/ossf.allstar.alert.v1alpha1.AlertSink/Alert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertSinkServer is the server API for AlertSink service.
// All implementations must embed UnimplementedAlertSinkServer
// for forward compatibility
type AlertSinkServer interface {
	Alert(context.Context, *AlertRequest) (*AlertResponse, error)
	mustEmbedUnimplementedAlertSinkServer()
}

// UnimplementedAlertSinkServer must be embedded to have forward compatible implementations.
type UnimplementedAlertSinkServer struct {
}

func (UnimplementedAlertSinkServer) Alert(context.Context, *AlertRequest) (*AlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alert not implemented")
}
func (UnimplementedAlertSinkServer) mustEmbedUnimplementedAlertSinkServer() {}

// UnsafeAlertSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertSinkServer will
// result in compilation errors.
type UnsafeAlertSinkServer interface {
	mustEmbedUnimplementedAlertSinkServer()
}

func RegisterAlertSinkServer(s grpc.ServiceRegistrar, srv AlertSinkServer) {
	s.RegisterService(&AlertSink_ServiceDesc, srv)
}

func _AlertSink_Alert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertSinkServer).Alert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ossf.allstar.alert.v1alpha1.AlertSink/Alert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertSinkServer).Alert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertSink_ServiceDesc is the grpc.ServiceDesc for AlertSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ossf.allstar.alert.v1alpha1.AlertSink",
	HandlerType: (*AlertSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alert",
			Handler:    _AlertSink_Alert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alert.proto",
}
